from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Settings (QtGui.QWidget):
    def __init__(self,settingsList = []):
        QtGui.QWidget.__init__(self)
        self.initUi()
        self.defaultList = [50,-50,100,-100,-100,-80,-80,100,100,80,
                            80,50,30,50,50,50,50,50,50,50,
                            50,50,30,10,-50,-50,-30,15,10,5,
                            -15,-10,-5]
        if settingsList:
            self.loadVal(settingsList)
    def getVal(self):
        li = []
        li.append(self.positiveSignalSpinBox.value())
        li.append(self.negativeSignalSpinBox.value())
        li.append(self.trendSpinBox.value())
        li.append(self.headAndShouldersSpinBox.value())
        li.append(self.tripleTopSpinBox.value())
        li.append(self.risingWedgeSpinBox.value())
        li.append(self.fallingTriangleSpinBox.value())
        li.append(self.reversedHeadAndShouldersSpinBox.value())
        li.append(self.tripleBottomSpinBox.value())
        li.append(self.fallingWedgeSpinBox.value())
        li.append(self.risingTriangleSpinBox.value())
        li.append(self.symetricTriangleSpinBox.value())
        li.append(self.rectangleSpinBox.value())
        li.append(self.oscilatorsSpinBox.value())
        li.append(self.newHighNewLowSpinBox.value())
        li.append(self.bollingerSpinBox.value())
        li.append(self.momentumSpinBox.value())
        li.append(self.rocSpinBox.value())
        li.append(self.cciSpinBox.value())
        li.append(self.rsiSpinBox.value())
        li.append(self.williamsSpinBox.value())
        li.append(self.risingBreakawayGapSpinBox.value())
        li.append(self.risingContinuationGapSpinBox.value())
        li.append(self.fallingExhaustionGapSpinBox.value())
        li.append(self.fallingBreakawayGapSpinBox.value())
        li.append(self.risingExhaustionGapSpinBox.value())
        li.append(self.fallingContinuationGapSpinBox.value())
        li.append(self.bull3SpinBox.value())
        li.append(self.morningStarSpinBox.value())
        li.append(self.bearSpinBox.value())
        li.append(self.piercingSpinBox.value())
        li.append(self.eveningStarSpinBox.value())
        li.append(self.darkCloudSpinBox.value())
        return li
        
        
    def loadVal(self,li = []):
        if not li:
            li = self.defaultList
        self.positiveSignalSpinBox.setValue(li[0])
        self.negativeSignalSpinBox.setValue(li[1])
        self.trendSpinBox.setValue( li[2])

        """Formacje"""
        #Odwrocenie trendu wzrostowego
        self.headAndShouldersSpinBox.setValue(li[3])
        self.tripleTopSpinBox.setValue(li[4])
        self.risingWedgeSpinBox.setValue(li[5])
        self.fallingTriangleSpinBox.setValue(li[6])

        #Odwrocenie trendu spadkowego
        self.reversedHeadAndShouldersSpinBox.setValue(li[7])
        self.tripleBottomSpinBox.setValue(li[8])
        self.fallingWedgeSpinBox.setValue(li[9])
        self.risingTriangleSpinBox.setValue(li[10])

        #Kontynuacja trendu
        self.symetricTriangleSpinBox.setValue(li[11])
        self.rectangleSpinBox.setValue(li[12])

        """Wskazniki i oscylatory"""
        self.oscilatorsSpinBox.setValue(li[13])
        self.newHighNewLowSpinBox.setValue(li[14])
        self.bollingerSpinBox.setValue(li[15])
        self.momentumSpinBox.setValue(li[16])
        self.rocSpinBox.setValue(li[17])
        self.cciSpinBox.setValue(li[18])
        self.rsiSpinBox.setValue(li[19])
        self.williamsSpinBox.setValue(li[20])

        """Luki"""
        #Wzrostowe
        self.risingBreakawayGapSpinBox.setValue(li[21])
        self.risingContinuationGapSpinBox.setValue(li[22])
        self.fallingExhaustionGapSpinBox.setValue(li[23])
        
        #Spadkowe
        self.fallingBreakawayGapSpinBox.setValue(li[24])
        self.risingExhaustionGapSpinBox.setValue(li[25])
        self.fallingContinuationGapSpinBox.setValue(li[26])

        """Formacje swiecowe"""
        #sygnal kupna
        self.bull3SpinBox.setValue(li[27])
        self.morningStarSpinBox.setValue(li[28])
        self.piercingSpinBox.setValue(li[29])

        #sygnal sprzedazy
        self.bearSpinBox.setValue(li[30])
        self.eveningStarSpinBox.setValue(li[31])
        self.darkCloudSpinBox.setValue(li[32])

    def initUi(self):
        self.resize(900, 610)
        self.setMaximumSize(QtCore.QSize(900, 610))

        self.gridLayout = QtGui.QGridLayout(self)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_18 = QtGui.QLabel(self)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout.addWidget(self.label_18, 2, 1, 1, 1)
        self.line_5 = QtGui.QFrame(self)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout.addWidget(self.line_5, 11, 3, 1, 1)
        self.risingTriangleCheckBox = QtGui.QCheckBox(self)
        self.risingTriangleCheckBox.setText(_fromUtf8(""))
        self.risingTriangleCheckBox.setObjectName(_fromUtf8("risingTriangleCheckBox"))
        self.gridLayout.addWidget(self.risingTriangleCheckBox, 17, 0, 1, 1)
        self.fallingTriangleCheckBox = QtGui.QCheckBox(self)
        self.fallingTriangleCheckBox.setText(_fromUtf8(""))
        self.fallingTriangleCheckBox.setObjectName(_fromUtf8("fallingTriangleCheckBox"))
        self.gridLayout.addWidget(self.fallingTriangleCheckBox, 12, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(self)
        self.checkBox_14.setText(_fromUtf8(""))
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridLayout.addWidget(self.checkBox_14, 2, 0, 1, 1)
        self.continuationOfTrendCheckBox = QtGui.QCheckBox(self)
        self.continuationOfTrendCheckBox.setText(_fromUtf8(""))
        self.continuationOfTrendCheckBox.setObjectName(_fromUtf8("continuationOfTrendCheckBox"))
        self.gridLayout.addWidget(self.continuationOfTrendCheckBox, 18, 0, 1, 1)
        self.oscilatorsCheckBox = QtGui.QCheckBox(self)
        self.oscilatorsCheckBox.setText(_fromUtf8(""))
        self.oscilatorsCheckBox.setObjectName(_fromUtf8("oscilatorsCheckBox"))
        self.gridLayout.addWidget(self.oscilatorsCheckBox, 1, 4, 1, 1)
        self.line_4 = QtGui.QFrame(self)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout.addWidget(self.line_4, 0, 7, 21, 1)
        self.label_36 = QtGui.QLabel(self)
        self.label_36.setIndent(15)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout.addWidget(self.label_36, 16, 5, 1, 1)
        self.cciSpinBox = QtGui.QSpinBox(self)
        self.cciSpinBox.setMaximum(100)
        self.cciSpinBox.setSingleStep(5)
        self.cciSpinBox.setProperty("value", 50)
        self.cciSpinBox.setObjectName(_fromUtf8("cciSpinBox"))
        self.gridLayout.addWidget(self.cciSpinBox, 6, 6, 1, 1)
        self.label_35 = QtGui.QLabel(self)
        self.label_35.setIndent(15)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout.addWidget(self.label_35, 15, 5, 1, 1)
        self.fallingExhaustionGapSpinBox = QtGui.QSpinBox(self)
        self.fallingExhaustionGapSpinBox.setMaximum(100)
        self.fallingExhaustionGapSpinBox.setSingleStep(5)
        self.fallingExhaustionGapSpinBox.setProperty("value", 10)
        self.fallingExhaustionGapSpinBox.setObjectName(_fromUtf8("fallingExhaustionGapSpinBox"))
        self.gridLayout.addWidget(self.fallingExhaustionGapSpinBox, 16, 6, 1, 1)
        self.risingContinuationGapSpinBox = QtGui.QSpinBox(self)
        self.risingContinuationGapSpinBox.setMaximum(100)
        self.risingContinuationGapSpinBox.setSingleStep(5)
        self.risingContinuationGapSpinBox.setProperty("value", 30)
        self.risingContinuationGapSpinBox.setObjectName(_fromUtf8("risingContinuationGapSpinBox"))
        self.gridLayout.addWidget(self.risingContinuationGapSpinBox, 15, 6, 1, 1)
        self.negativeSignalSpinBox = QtGui.QSpinBox(self)
        self.negativeSignalSpinBox.setMinimum(-100)
        self.negativeSignalSpinBox.setMaximum(0)
        self.negativeSignalSpinBox.setSingleStep(5)
        self.negativeSignalSpinBox.setProperty("value", -50)
        self.negativeSignalSpinBox.setObjectName(_fromUtf8("negativeSignalSpinBox"))
        self.gridLayout.addWidget(self.negativeSignalSpinBox, 1, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self)
        self.label_23.setIndent(0)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout.addWidget(self.label_23, 4, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 2)
        self.reversalOfRisingTrendCheckBox = QtGui.QCheckBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reversalOfRisingTrendCheckBox.sizePolicy().hasHeightForWidth())
        self.reversalOfRisingTrendCheckBox.setSizePolicy(sizePolicy)
        self.reversalOfRisingTrendCheckBox.setText(_fromUtf8(""))
        self.reversalOfRisingTrendCheckBox.setObjectName(_fromUtf8("reversalOfRisingTrendCheckBox"))
        self.gridLayout.addWidget(self.reversalOfRisingTrendCheckBox, 5, 0, 1, 1)
        self.bull3SpinBox = QtGui.QSpinBox(self)
        self.bull3SpinBox.setMaximum(100)
        self.bull3SpinBox.setSingleStep(5)
        self.bull3SpinBox.setProperty("value", 15)
        self.bull3SpinBox.setObjectName(_fromUtf8("bull3SpinBox"))
        self.gridLayout.addWidget(self.bull3SpinBox, 2, 10, 1, 1)
        self.label_31 = QtGui.QLabel(self)
        self.label_31.setIndent(15)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 4, 9, 1, 1)
        self.label_4 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_4.setFrameShadow(QtGui.QFrame.Plain)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 9, 1, 2)
        self.bearSpinBox = QtGui.QSpinBox(self)
        self.bearSpinBox.setMinimum(-100)
        self.bearSpinBox.setMaximum(0)
        self.bearSpinBox.setSingleStep(5)
        self.bearSpinBox.setProperty("value", -15)
        self.bearSpinBox.setObjectName(_fromUtf8("bearSpinBox"))
        self.gridLayout.addWidget(self.bearSpinBox, 6, 10, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 21, 1, 1, 10)
        self.label_22 = QtGui.QLabel(self)
        self.label_22.setIndent(0)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout.addWidget(self.label_22, 3, 5, 1, 1)
        self.label_32 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setFrameShape(QtGui.QFrame.StyledPanel) 
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout.addWidget(self.label_32, 12, 5, 1, 2)
        self.label_29 = QtGui.QLabel(self)
        self.label_29.setIndent(15)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout.addWidget(self.label_29, 2, 9, 1, 1)
        self.oscilatorsSpinBox = QtGui.QSpinBox(self)
        self.oscilatorsSpinBox.setMaximum(100)
        self.oscilatorsSpinBox.setSingleStep(5)
        self.oscilatorsSpinBox.setProperty("value", 50)
        self.oscilatorsSpinBox.setObjectName(_fromUtf8("oscilatorsSpinBox"))
        self.gridLayout.addWidget(self.oscilatorsSpinBox, 1, 6, 1, 1)
        self.label_7 = QtGui.QLabel(self)
        self.label_7.setIndent(15)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 10, 1, 1, 1)
        self.reversedHeadAndShouldersSpinBox = QtGui.QSpinBox(self)
        self.reversedHeadAndShouldersSpinBox.setMinimum(0)
        self.reversedHeadAndShouldersSpinBox.setMaximum(100)
        self.reversedHeadAndShouldersSpinBox.setSingleStep(5)
        self.reversedHeadAndShouldersSpinBox.setProperty("value", 100)
        self.reversedHeadAndShouldersSpinBox.setObjectName(_fromUtf8("reversedHeadAndShouldersSpinBox"))
        self.gridLayout.addWidget(self.reversedHeadAndShouldersSpinBox, 14, 2, 1, 1)
        self.risingBreakawayGapSpinBox = QtGui.QSpinBox(self)
        self.risingBreakawayGapSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.risingBreakawayGapSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.risingBreakawayGapSpinBox.setMaximum(100)
        self.risingBreakawayGapSpinBox.setSingleStep(5)
        self.risingBreakawayGapSpinBox.setProperty("value", 50)
        self.risingBreakawayGapSpinBox.setObjectName(_fromUtf8("risingBreakawayGapSpinBox"))
        self.gridLayout.addWidget(self.risingBreakawayGapSpinBox, 14, 6, 1, 1)
        self.risingWedgeSpinBox = QtGui.QSpinBox(self)
        self.risingWedgeSpinBox.setMinimum(-100)
        self.risingWedgeSpinBox.setMaximum(0)
        self.risingWedgeSpinBox.setSingleStep(5)
        self.risingWedgeSpinBox.setProperty("value", -80)
        self.risingWedgeSpinBox.setObjectName(_fromUtf8("risingWedgeSpinBox"))
        self.gridLayout.addWidget(self.risingWedgeSpinBox, 10, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self)
        self.label_27.setIndent(0)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout.addWidget(self.label_27, 10, 5, 1, 1)
        self.williamsSpinBox = QtGui.QSpinBox(self)
        self.williamsSpinBox.setMaximum(100)
        self.williamsSpinBox.setSingleStep(5)
        self.williamsSpinBox.setProperty("value", 50)
        self.williamsSpinBox.setObjectName(_fromUtf8("williamsSpinBox"))
        self.gridLayout.addWidget(self.williamsSpinBox, 10, 6, 1, 1)
        self.fallingTriangleSpinBox = QtGui.QSpinBox(self)
        self.fallingTriangleSpinBox.setMinimum(-100)
        self.fallingTriangleSpinBox.setMaximum(0)
        self.fallingTriangleSpinBox.setSingleStep(5)
        self.fallingTriangleSpinBox.setProperty("value", -80)
        self.fallingTriangleSpinBox.setObjectName(_fromUtf8("fallingTriangleSpinBox"))
        self.gridLayout.addWidget(self.fallingTriangleSpinBox, 12, 2, 1, 1)
        self.fallingBreakawayGapSpinBox = QtGui.QSpinBox(self)
        self.fallingBreakawayGapSpinBox.setMinimum(-100)
        self.fallingBreakawayGapSpinBox.setMaximum(0)
        self.fallingBreakawayGapSpinBox.setSingleStep(5)
        self.fallingBreakawayGapSpinBox.setProperty("value", -50)
        self.fallingBreakawayGapSpinBox.setObjectName(_fromUtf8("fallingBreakawayGapSpiBox"))
        self.gridLayout.addWidget(self.fallingBreakawayGapSpinBox, 18, 6, 1, 1)
        self.defaultPushButton = QtGui.QPushButton(self)
        self.defaultPushButton.setStyleSheet(_fromUtf8("border-left-color: rgb(137, 255, 177);"))
        self.defaultPushButton.setObjectName(_fromUtf8("defaultPushButton"))
        self.gridLayout.addWidget(self.defaultPushButton, 18, 10, 1, 1)
        self.label_28 = QtGui.QLabel(self)
        self.label_28.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout.addWidget(self.label_28, 1, 9, 1, 2)
        self.label_42 = QtGui.QLabel(self)
        self.label_42.setIndent(15)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout.addWidget(self.label_42, 6, 9, 1, 1)
        self.label_9 = QtGui.QLabel(self)
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_9.setIndent(0)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 13, 1, 1, 2)
        self.label_15 = QtGui.QLabel(self)
        self.label_15.setIndent(15)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout.addWidget(self.label_15, 19, 1, 1, 2)
        self.label_33 = QtGui.QLabel(self)
        self.label_33.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout.addWidget(self.label_33, 13, 5, 1, 2)
        self.label_19 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout.addWidget(self.label_19, 0, 5, 1, 2)
        self.symetricTriangleSpinBox = QtGui.QSpinBox(self)
        self.symetricTriangleSpinBox.setMaximum(100)
        self.symetricTriangleSpinBox.setSingleStep(5)
        self.symetricTriangleSpinBox.setProperty("value", 50)
        self.symetricTriangleSpinBox.setObjectName(_fromUtf8("symetricTriangleSpinBox"))
        self.gridLayout.addWidget(self.symetricTriangleSpinBox, 19, 2, 1, 1)
        self.rsiSpinBox = QtGui.QSpinBox(self)
        self.rsiSpinBox.setMaximum(100)
        self.rsiSpinBox.setSingleStep(5)
        self.rsiSpinBox.setProperty("value", 50)
        self.rsiSpinBox.setObjectName(_fromUtf8("rsiSpinBox"))
        self.gridLayout.addWidget(self.rsiSpinBox, 9, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self)
        self.label_2.setIndent(15)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 9, 1, 1, 1)
        self.fallingContinuationGapSpinBox = QtGui.QSpinBox(self)
        self.fallingContinuationGapSpinBox.setMinimum(-100)
        self.fallingContinuationGapSpinBox.setMaximum(0)
        self.fallingContinuationGapSpinBox.setSingleStep(5)
        self.fallingContinuationGapSpinBox.setProperty("value", -30)
        self.fallingContinuationGapSpinBox.setObjectName(_fromUtf8("fallingConrinuationGapSpinBox"))
        self.gridLayout.addWidget(self.fallingContinuationGapSpinBox, 20, 6, 1, 1)
        self.label_30 = QtGui.QLabel(self)
        self.label_30.setIndent(15)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout.addWidget(self.label_30, 3, 9, 1, 1)
        self.label_26 = QtGui.QLabel(self)
        self.label_26.setIndent(0)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 9, 5, 1, 1)
        self.rocSpinBox = QtGui.QSpinBox(self)
        self.rocSpinBox.setMaximum(100)
        self.rocSpinBox.setSingleStep(5)
        self.rocSpinBox.setProperty("value", 50)
        self.rocSpinBox.setObjectName(_fromUtf8("rocSpinBox"))
        self.gridLayout.addWidget(self.rocSpinBox, 5, 6, 1, 1)
        self.label_21 = QtGui.QLabel(self)
        self.label_21.setIndent(0)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout.addWidget(self.label_21, 2, 5, 1, 1)
        self.label_25 = QtGui.QLabel(self)
        self.label_25.setIndent(0)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout.addWidget(self.label_25, 6, 5, 1, 1)
        self.label_43 = QtGui.QLabel(self)
        self.label_43.setIndent(15)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout.addWidget(self.label_43, 9, 9, 1, 1)
        self.label_5 = QtGui.QLabel(self)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.label_5.setFrameShadow(QtGui.QFrame.Plain)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setIndent(-5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 2)
        self.label_41 = QtGui.QLabel(self)
        self.label_41.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout.addWidget(self.label_41, 5, 9, 1, 2)
        self.label_8 = QtGui.QLabel(self)
        self.label_8.setIndent(15)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 12, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self)
        self.label_39.setIndent(15)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout.addWidget(self.label_39, 19, 5, 1, 1)
        self.label_3 = QtGui.QLabel(self)
        self.label_3.setIndent(15)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 6, 1, 1, 1)
        self.risingExhaustionGapSpinBox = QtGui.QSpinBox(self)
        self.risingExhaustionGapSpinBox.setMinimum(-100)
        self.risingExhaustionGapSpinBox.setMaximum(0)
        self.risingExhaustionGapSpinBox.setSingleStep(5)
        self.risingExhaustionGapSpinBox.setProperty("value", -50)
        self.risingExhaustionGapSpinBox.setObjectName(_fromUtf8("risingExhaustionGapSpinBox"))
        self.gridLayout.addWidget(self.risingExhaustionGapSpinBox, 19, 6, 1, 1)
        self.piercingSpinBox = QtGui.QSpinBox(self)
        self.piercingSpinBox.setMaximum(100)
        self.piercingSpinBox.setSingleStep(5)
        self.piercingSpinBox.setProperty("value", 5)
        self.piercingSpinBox.setObjectName(_fromUtf8("piercingSpinBox"))
        self.gridLayout.addWidget(self.piercingSpinBox, 4, 10, 1, 1)
        self.risingTriangleSpinBox = QtGui.QSpinBox(self)
        self.risingTriangleSpinBox.setMaximum(100)
        self.risingTriangleSpinBox.setSingleStep(5)
        self.risingTriangleSpinBox.setProperty("value", 80)
        self.risingTriangleSpinBox.setObjectName(_fromUtf8("risingTriangleSpinBox"))
        self.gridLayout.addWidget(self.risingTriangleSpinBox, 17, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self)
        self.label_13.setIndent(15)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 17, 1, 1, 1)
        self.positiveSignalSpinBox = QtGui.QSpinBox(self)
        self.positiveSignalSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.positiveSignalSpinBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.positiveSignalSpinBox.setMaximum(100)
        self.positiveSignalSpinBox.setSingleStep(5)
        self.positiveSignalSpinBox.setProperty("value", 50)
        self.positiveSignalSpinBox.setObjectName(_fromUtf8("positiveSignalSpinBox"))
        self.gridLayout.addWidget(self.positiveSignalSpinBox, 0, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self)
        self.label_16.setIndent(15)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout.addWidget(self.label_16, 20, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 19, 10, 1, 1)
        self.label_20 = QtGui.QLabel(self)
        self.label_20.setIndent(0)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 1, 5, 1, 1)
        self.trendSpinBox = QtGui.QSpinBox(self)
        self.trendSpinBox.setMaximum(100)
        self.trendSpinBox.setSingleStep(5)
        self.trendSpinBox.setProperty("value", 100)
        self.trendSpinBox.setObjectName(_fromUtf8("trendSpinBox"))
        self.gridLayout.addWidget(self.trendSpinBox, 2, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self)
        self.label_24.setIndent(0)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 5, 5, 1, 1)
        self.bollingerSpinBox = QtGui.QSpinBox(self)
        self.bollingerSpinBox.setMaximum(100)
        self.bollingerSpinBox.setSingleStep(5)
        self.bollingerSpinBox.setProperty("value", 50)
        self.bollingerSpinBox.setObjectName(_fromUtf8("BollingerSpinBox"))
        self.gridLayout.addWidget(self.bollingerSpinBox, 3, 6, 1, 1)
        self.label_44 = QtGui.QLabel(self)
        self.label_44.setIndent(15)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout.addWidget(self.label_44, 10, 9, 1, 1)
        self.label_40 = QtGui.QLabel(self)
        self.label_40.setIndent(15)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout.addWidget(self.label_40, 20, 5, 1, 1)
        self.label_38 = QtGui.QLabel(self)
        self.label_38.setIndent(15)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout.addWidget(self.label_38, 18, 5, 1, 1)
        self.newHighNewLowSpinBox = QtGui.QSpinBox(self)
        self.newHighNewLowSpinBox.setMaximum(100)
        self.newHighNewLowSpinBox.setSingleStep(5)
        self.newHighNewLowSpinBox.setProperty("value", 50)
        self.newHighNewLowSpinBox.setObjectName(_fromUtf8("newHighNewLowSpinBox"))
        self.gridLayout.addWidget(self.newHighNewLowSpinBox, 2, 6, 1, 1)
        self.tripleTopSpinBox = QtGui.QSpinBox(self)
        self.tripleTopSpinBox.setMinimum(-100)
        self.tripleTopSpinBox.setMaximum(0)
        self.tripleTopSpinBox.setSingleStep(5)
        self.tripleTopSpinBox.setProperty("value", -100)
        self.tripleTopSpinBox.setObjectName(_fromUtf8("tripleTopSpinBox"))
        self.gridLayout.addWidget(self.tripleTopSpinBox, 9, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self)
        self.label_34.setIndent(15)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout.addWidget(self.label_34, 14, 5, 1, 1)
        self.tripleBottomSpinBox = QtGui.QSpinBox(self)
        self.tripleBottomSpinBox.setMaximum(100)
        self.tripleBottomSpinBox.setSingleStep(5)
        self.tripleBottomSpinBox.setProperty("value", 100)
        self.tripleBottomSpinBox.setObjectName(_fromUtf8("tripleBottomSpinBox"))
        self.gridLayout.addWidget(self.tripleBottomSpinBox, 15, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self)
        self.label_11.setIndent(15)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 15, 1, 1, 1)
        self.morningStarSpinBox = QtGui.QSpinBox(self)
        self.morningStarSpinBox.setMaximum(100)
        self.morningStarSpinBox.setSingleStep(5)
        self.morningStarSpinBox.setProperty("value", 10)
        self.morningStarSpinBox.setObjectName(_fromUtf8("morningStarSpinBox"))
        self.gridLayout.addWidget(self.morningStarSpinBox, 3, 10, 1, 1)
        self.label = QtGui.QLabel(self)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label.setIndent(0)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 5, 1, 1, 2)
        self.fallingWedgeSpinBox = QtGui.QSpinBox(self)
        self.fallingWedgeSpinBox.setMaximum(100)
        self.fallingWedgeSpinBox.setSingleStep(5)
        self.fallingWedgeSpinBox.setProperty("value", 80)
        self.fallingWedgeSpinBox.setObjectName(_fromUtf8("fallingWedgeSpinBox"))
        self.gridLayout.addWidget(self.fallingWedgeSpinBox, 16, 2, 1, 1)
        self.eveningStarSpinBox = QtGui.QSpinBox(self)
        self.eveningStarSpinBox.setMinimum(-100)
        self.eveningStarSpinBox.setMaximum(0)
        self.eveningStarSpinBox.setSingleStep(5)
        self.eveningStarSpinBox.setProperty("value", -10)
        self.eveningStarSpinBox.setObjectName(_fromUtf8("eveningStarSpinBox"))
        self.gridLayout.addWidget(self.eveningStarSpinBox, 9, 10, 1, 1)
        self.label_12 = QtGui.QLabel(self)
        self.label_12.setIndent(15)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 16, 1, 1, 1)
        self.headAndShouldersSpinBox = QtGui.QSpinBox(self)
        self.headAndShouldersSpinBox.setMinimum(-100)
        self.headAndShouldersSpinBox.setMaximum(0)
        self.headAndShouldersSpinBox.setSingleStep(5)
        self.headAndShouldersSpinBox.setProperty("value", -100)
        self.headAndShouldersSpinBox.setObjectName(_fromUtf8("HeadAndShouldersSpinBox"))
        self.gridLayout.addWidget(self.headAndShouldersSpinBox, 6, 2, 1, 1)
        self.momentumSpinBox = QtGui.QSpinBox(self)
        self.momentumSpinBox.setMaximum(100)
        self.momentumSpinBox.setSingleStep(5)
        self.momentumSpinBox.setProperty("value", 50)
        self.momentumSpinBox.setObjectName(_fromUtf8("momentumSpinBox"))
        self.gridLayout.addWidget(self.momentumSpinBox, 4, 6, 1, 1)
        self.darkCloudSpinBox = QtGui.QSpinBox(self)
        self.darkCloudSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.darkCloudSpinBox.setMinimum(-100)
        self.darkCloudSpinBox.setMaximum(0)
        self.darkCloudSpinBox.setSingleStep(5)
        self.darkCloudSpinBox.setProperty("value", -5)
        self.darkCloudSpinBox.setObjectName(_fromUtf8("darkCloudSpinBox"))
        self.gridLayout.addWidget(self.darkCloudSpinBox, 10, 10, 1, 1)
        self.label_10 = QtGui.QLabel(self)
        self.label_10.setIndent(15)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 14, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self)
        self.label_37.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_37.setIndent(0)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 17, 5, 1, 2)
        self.label_14 = QtGui.QLabel(self)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(226, 226, 226);"))
        self.label_14.setIndent(0)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 18, 1, 1, 2)
        self.rectangleSpinBox = QtGui.QSpinBox(self)
        self.rectangleSpinBox.setMaximum(100)
        self.rectangleSpinBox.setSingleStep(5)
        self.rectangleSpinBox.setProperty("value", 30)
        self.rectangleSpinBox.setObjectName(_fromUtf8("rectangleSpinBox"))
        self.gridLayout.addWidget(self.rectangleSpinBox, 20, 2, 1, 1)
        self.rectangleCheckBox = QtGui.QCheckBox(self)
        self.rectangleCheckBox.setText(_fromUtf8(""))
        self.rectangleCheckBox.setObjectName(_fromUtf8("rectangleCheckBox"))
        self.gridLayout.addWidget(self.rectangleCheckBox, 20, 0, 1, 1)
        self.momentumCheckBox = QtGui.QCheckBox(self)
        self.momentumCheckBox.setText(_fromUtf8(""))
        self.momentumCheckBox.setObjectName(_fromUtf8("momentumCheckBox"))
        self.gridLayout.addWidget(self.momentumCheckBox, 4, 4, 1, 1)
        self.rocCheckBox = QtGui.QCheckBox(self)
        self.rocCheckBox.setText(_fromUtf8(""))
        self.rocCheckBox.setObjectName(_fromUtf8("rocCheckBox"))
        self.gridLayout.addWidget(self.rocCheckBox, 5, 4, 1, 1)
        self.rsiCheckBox = QtGui.QCheckBox(self)
        self.rsiCheckBox.setText(_fromUtf8(""))
        self.rsiCheckBox.setObjectName(_fromUtf8("rsiCheckBox"))
        self.gridLayout.addWidget(self.rsiCheckBox, 9, 4, 1, 1)
        self.risingContinuationGapCheckBox = QtGui.QCheckBox(self)
        self.risingContinuationGapCheckBox.setText(_fromUtf8(""))
        self.risingContinuationGapCheckBox.setObjectName(_fromUtf8("risingContinuationGapCheckBox"))
        self.gridLayout.addWidget(self.risingContinuationGapCheckBox, 15, 4, 1, 1)
        self.risingBreakawayGapCheckBox = QtGui.QCheckBox(self)
        self.risingBreakawayGapCheckBox.setText(_fromUtf8(""))
        self.risingBreakawayGapCheckBox.setObjectName(_fromUtf8("risingBreakawayGapCheckBox"))
        self.gridLayout.addWidget(self.risingBreakawayGapCheckBox, 14, 4, 1, 1)
        self.headAndShouldersCheckBox = QtGui.QCheckBox(self)
        self.headAndShouldersCheckBox.setText(_fromUtf8(""))
        self.headAndShouldersCheckBox.setObjectName(_fromUtf8("headAndShouldersCheckBox"))
        self.gridLayout.addWidget(self.headAndShouldersCheckBox, 6, 0, 1, 1)
        self.symetricTriangleCheckBox = QtGui.QCheckBox(self)
        self.symetricTriangleCheckBox.setText(_fromUtf8(""))
        self.symetricTriangleCheckBox.setObjectName(_fromUtf8("symetricTriangleCheckBox"))
        self.gridLayout.addWidget(self.symetricTriangleCheckBox, 19, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 2)
        self.tripleTopCheckBox = QtGui.QCheckBox(self)
        self.tripleTopCheckBox.setText(_fromUtf8(""))
        self.tripleTopCheckBox.setObjectName(_fromUtf8("tripleTopCheckBox"))
        self.gridLayout.addWidget(self.tripleTopCheckBox, 9, 0, 1, 1)
        self.risingWedgeCheckBox = QtGui.QCheckBox(self)
        self.risingWedgeCheckBox.setText(_fromUtf8(""))
        self.risingWedgeCheckBox.setObjectName(_fromUtf8("risingWedgeCheckBox"))
        self.gridLayout.addWidget(self.risingWedgeCheckBox, 10, 0, 1, 1)
        self.reversalOfFallingTrendCheckBox = QtGui.QCheckBox(self)
        self.reversalOfFallingTrendCheckBox.setText(_fromUtf8(""))
        self.reversalOfFallingTrendCheckBox.setObjectName(_fromUtf8("reversalOfFallingTrendCheckBox"))
        self.gridLayout.addWidget(self.reversalOfFallingTrendCheckBox, 13, 0, 1, 1)
        self.reservedHeadAndShouldersCheckBox = QtGui.QCheckBox(self)
        self.reservedHeadAndShouldersCheckBox.setText(_fromUtf8(""))
        self.reservedHeadAndShouldersCheckBox.setObjectName(_fromUtf8("reservedHeadAndShouldersCheckBox"))
        self.gridLayout.addWidget(self.reservedHeadAndShouldersCheckBox, 14, 0, 1, 1)
        self.tripleBottomCheckBox = QtGui.QCheckBox(self)
        self.tripleBottomCheckBox.setText(_fromUtf8(""))
        self.tripleBottomCheckBox.setObjectName(_fromUtf8("tripleBottomCheckBox"))
        self.gridLayout.addWidget(self.tripleBottomCheckBox, 15, 0, 1, 1)
        self.line_3 = QtGui.QFrame(self)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 3, 0, 1, 3)
        self.fallingWedgeCheckBox = QtGui.QCheckBox(self)
        self.fallingWedgeCheckBox.setText(_fromUtf8(""))
        self.fallingWedgeCheckBox.setObjectName(_fromUtf8("fallingWedgeCheckBox"))
        self.gridLayout.addWidget(self.fallingWedgeCheckBox, 16, 0, 1, 1)
        self.fallingContinuationGapCheckBox = QtGui.QCheckBox(self)
        self.fallingContinuationGapCheckBox.setText(_fromUtf8(""))
        self.fallingContinuationGapCheckBox.setObjectName(_fromUtf8("fallingContinuationGapCheckBox"))
        self.gridLayout.addWidget(self.fallingContinuationGapCheckBox, 20, 4, 1, 1)
        self.formationsCheckBox = QtGui.QCheckBox(self)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.formationsCheckBox.setFont(font)
        self.formationsCheckBox.setText(_fromUtf8(""))
        self.formationsCheckBox.setCheckable(True)
        self.formationsCheckBox.setTristate(False)
        self.formationsCheckBox.setObjectName(_fromUtf8("formationsCheckBox"))
        self.gridLayout.addWidget(self.formationsCheckBox, 4, 0, 1, 1)
        self.bollingerCheckBox = QtGui.QCheckBox(self)
        self.bollingerCheckBox.setText(_fromUtf8(""))
        self.bollingerCheckBox.setObjectName(_fromUtf8("bollingerCheckBox"))
        self.gridLayout.addWidget(self.bollingerCheckBox, 3, 4, 1, 1)
        self.gapsCheckBox = QtGui.QCheckBox(self)
        self.gapsCheckBox.setText(_fromUtf8(""))
        self.gapsCheckBox.setObjectName(_fromUtf8("gapsCheckBox"))
        self.gridLayout.addWidget(self.gapsCheckBox, 12, 4, 1, 1)
        self.newHighNewLowCheckBox = QtGui.QCheckBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newHighNewLowCheckBox.sizePolicy().hasHeightForWidth())
        self.newHighNewLowCheckBox.setSizePolicy(sizePolicy)
        self.newHighNewLowCheckBox.setText(_fromUtf8(""))
        self.newHighNewLowCheckBox.setObjectName(_fromUtf8("newHighNewLowCheckBox"))
        self.gridLayout.addWidget(self.newHighNewLowCheckBox, 2, 4, 1, 1)
        self.fallingExhaustionGapCheckBox = QtGui.QCheckBox(self)
        self.fallingExhaustionGapCheckBox.setText(_fromUtf8(""))
        self.fallingExhaustionGapCheckBox.setObjectName(_fromUtf8("fallingExhaustionGapCheckBox"))
        self.gridLayout.addWidget(self.fallingExhaustionGapCheckBox, 16, 4, 1, 1)
        self.indicatorsAndOscilatorsCheckBox = QtGui.QCheckBox(self)
        self.indicatorsAndOscilatorsCheckBox.setText(_fromUtf8(""))
        self.indicatorsAndOscilatorsCheckBox.setObjectName(_fromUtf8("indicatorsAndOscilatorsCheckBox"))
        self.gridLayout.addWidget(self.indicatorsAndOscilatorsCheckBox, 0, 4, 1, 1)
        self.cciCheckBox = QtGui.QCheckBox(self)
        self.cciCheckBox.setText(_fromUtf8(""))
        self.cciCheckBox.setObjectName(_fromUtf8("cciCheckBox"))
        self.gridLayout.addWidget(self.cciCheckBox, 6, 4, 1, 1)
        self.line = QtGui.QFrame(self)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 0, 3, 21, 1)
        self.williamsCheckBox = QtGui.QCheckBox(self)
        self.williamsCheckBox.setText(_fromUtf8(""))
        self.williamsCheckBox.setObjectName(_fromUtf8("williamsCheckBox"))
        self.gridLayout.addWidget(self.williamsCheckBox, 10, 4, 1, 1)
        self.risingGapsCheckBox = QtGui.QCheckBox(self)
        self.risingGapsCheckBox.setText(_fromUtf8(""))
        self.risingGapsCheckBox.setObjectName(_fromUtf8("risingGapsCheckBox"))
        self.gridLayout.addWidget(self.risingGapsCheckBox, 13, 4, 1, 1)
        self.risingExhaustionCheckBox = QtGui.QCheckBox(self)
        self.risingExhaustionCheckBox.setText(_fromUtf8(""))
        self.risingExhaustionCheckBox.setObjectName(_fromUtf8("risingExhaustionCheckBox"))
        self.gridLayout.addWidget(self.risingExhaustionCheckBox, 19, 4, 1, 1)
        self.fallingBreakawayGapCheckBox = QtGui.QCheckBox(self)
        self.fallingBreakawayGapCheckBox.setText(_fromUtf8(""))
        self.fallingBreakawayGapCheckBox.setObjectName(_fromUtf8("fallingBreakawayGapCheckBox"))
        self.gridLayout.addWidget(self.fallingBreakawayGapCheckBox, 18, 4, 1, 1)
        self.fallingGapsCheckBox = QtGui.QCheckBox(self)
        self.fallingGapsCheckBox.setText(_fromUtf8(""))
        self.fallingGapsCheckBox.setObjectName(_fromUtf8("fallingGapsCheckBox"))
        self.gridLayout.addWidget(self.fallingGapsCheckBox, 17, 4, 1, 1)
        self.buySignalCheckBox = QtGui.QCheckBox(self)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buySignalCheckBox.sizePolicy().hasHeightForWidth())
        self.buySignalCheckBox.setSizePolicy(sizePolicy)
        self.buySignalCheckBox.setText(_fromUtf8(""))
        self.buySignalCheckBox.setObjectName(_fromUtf8("buySignalCheckBox"))
        self.gridLayout.addWidget(self.buySignalCheckBox, 1, 8, 1, 1)
        self.bull3CheckBox = QtGui.QCheckBox(self)
        self.bull3CheckBox.setText(_fromUtf8(""))
        self.bull3CheckBox.setObjectName(_fromUtf8("bull3CheckBox"))
        self.gridLayout.addWidget(self.bull3CheckBox, 2, 8, 1, 1)
        self.morningStarCheckBox = QtGui.QCheckBox(self)
        self.morningStarCheckBox.setText(_fromUtf8(""))
        self.morningStarCheckBox.setObjectName(_fromUtf8("morningStarCheckBox"))
        self.gridLayout.addWidget(self.morningStarCheckBox, 3, 8, 1, 1)
        self.piercingCheckBox = QtGui.QCheckBox(self)
        self.piercingCheckBox.setText(_fromUtf8(""))
        self.piercingCheckBox.setObjectName(_fromUtf8("piercingCheckBox"))
        self.gridLayout.addWidget(self.piercingCheckBox, 4, 8, 1, 1)
        self.sellSignalCheckBox = QtGui.QCheckBox(self)
        self.sellSignalCheckBox.setText(_fromUtf8(""))
        self.sellSignalCheckBox.setObjectName(_fromUtf8("sellSignalCheckBox"))
        self.gridLayout.addWidget(self.sellSignalCheckBox, 5, 8, 1, 1)
        self.bearCheckBox = QtGui.QCheckBox(self)
        self.bearCheckBox.setText(_fromUtf8(""))
        self.bearCheckBox.setObjectName(_fromUtf8("bearCheckBox"))
        self.gridLayout.addWidget(self.bearCheckBox, 6, 8, 1, 1)
        self.eveningStarCheckBox = QtGui.QCheckBox(self)
        self.eveningStarCheckBox.setText(_fromUtf8(""))
        self.eveningStarCheckBox.setObjectName(_fromUtf8("eveningStarCheckBox"))
        self.gridLayout.addWidget(self.eveningStarCheckBox, 9, 8, 1, 1)
        self.darkCloudCheckBox = QtGui.QCheckBox(self)
        self.darkCloudCheckBox.setText(_fromUtf8(""))
        self.darkCloudCheckBox.setObjectName(_fromUtf8("darkCloudCheckBox"))
        self.gridLayout.addWidget(self.darkCloudCheckBox, 10, 8, 1, 1)
        self.candlesticPatternsCheckBox = QtGui.QCheckBox(self)
        self.candlesticPatternsCheckBox.setText(_fromUtf8(""))
        self.candlesticPatternsCheckBox.setObjectName(_fromUtf8("candlesticPatternsCheckBox"))
        self.gridLayout.addWidget(self.candlesticPatternsCheckBox, 0, 8, 1, 1)

        self.retranslateUi(self)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reversalOfRisingTrendCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.headAndShouldersCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingWedgeCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingTriangleCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reversalOfFallingTrendCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reservedHeadAndShouldersCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleBottomCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingWedgeCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingTriangleCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.continuationOfTrendCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.symetricTriangleCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rectangleCheckBox.setOn)
        QtCore.QObject.connect(self.formationsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleTopCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.headAndShouldersCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleTopCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingWedgeCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfRisingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingTriangleCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.reservedHeadAndShouldersCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.tripleBottomCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingWedgeCheckBox.setOn)
        QtCore.QObject.connect(self.reversalOfFallingTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingTriangleCheckBox.setOn)
        QtCore.QObject.connect(self.continuationOfTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.symetricTriangleCheckBox.setOn)
        QtCore.QObject.connect(self.continuationOfTrendCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rectangleCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.oscilatorsCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.newHighNewLowCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bollingerCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.momentumCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rocCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.cciCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.rsiCheckBox.setOn)
        QtCore.QObject.connect(self.indicatorsAndOscilatorsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.williamsCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingGapsCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingBreakawayGapCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingContinuationGapCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingExhaustionGapCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingGapsCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingBreakawayGapCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingExhaustionCheckBox.setOn)
        QtCore.QObject.connect(self.gapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingContinuationGapCheckBox.setOn)
        QtCore.QObject.connect(self.risingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingBreakawayGapCheckBox.setOn)
        QtCore.QObject.connect(self.risingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingContinuationGapCheckBox.setOn)
        QtCore.QObject.connect(self.risingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingExhaustionGapCheckBox.setOn)
        QtCore.QObject.connect(self.fallingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingBreakawayGapCheckBox.setOn)
        QtCore.QObject.connect(self.fallingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.risingExhaustionCheckBox.setOn)
        QtCore.QObject.connect(self.fallingGapsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.fallingContinuationGapCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.buySignalCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bull3CheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.morningStarCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.piercingCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.sellSignalCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bearCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.eveningStarCheckBox.setOn)
        QtCore.QObject.connect(self.candlesticPatternsCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.darkCloudCheckBox.setOn)
        QtCore.QObject.connect(self.buySignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bull3CheckBox.setOn)
        QtCore.QObject.connect(self.buySignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.morningStarCheckBox.setOn)
        QtCore.QObject.connect(self.buySignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.piercingCheckBox.setOn)
        QtCore.QObject.connect(self.sellSignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.darkCloudCheckBox.setOn)
        QtCore.QObject.connect(self.sellSignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.bearCheckBox.setOn)
        QtCore.QObject.connect(self.sellSignalCheckBox, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.eveningStarCheckBox.setOn)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
            Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
            self.label_18.setText(QtGui.QApplication.translate("Form", "Trend", None, QtGui.QApplication.UnicodeUTF8))
            self.label_36.setText(QtGui.QApplication.translate("Form", "Falling Exhaustion Gap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_35.setText(QtGui.QApplication.translate("Form", "Rising Continuation Gap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_23.setText(QtGui.QApplication.translate("Form", "Momentum", None, QtGui.QApplication.UnicodeUTF8))
            self.label_6.setText(QtGui.QApplication.translate("Form", "Positive Signal", None, QtGui.QApplication.UnicodeUTF8))
            self.label_31.setText(QtGui.QApplication.translate("Form", "Piercing", None, QtGui.QApplication.UnicodeUTF8))
            self.label_4.setText(QtGui.QApplication.translate("Form", "Candlestick Patterns ", None, QtGui.QApplication.UnicodeUTF8))
            self.label_22.setText(QtGui.QApplication.translate("Form", "Bollinger", None, QtGui.QApplication.UnicodeUTF8))
            self.label_32.setText(QtGui.QApplication.translate("Form", "Gaps", None, QtGui.QApplication.UnicodeUTF8))
            self.label_29.setText(QtGui.QApplication.translate("Form", "Bull 3", None, QtGui.QApplication.UnicodeUTF8))
            self.label_7.setText(QtGui.QApplication.translate("self", "Rising Wedge", None, QtGui.QApplication.UnicodeUTF8))
            self.label_27.setText(QtGui.QApplication.translate("Form", "Williams", None, QtGui.QApplication.UnicodeUTF8))
            self.defaultPushButton.setText(QtGui.QApplication.translate("Form", "Default", None, QtGui.QApplication.UnicodeUTF8))
            self.label_28.setText(QtGui.QApplication.translate("Form", "Buy singal:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_42.setText(QtGui.QApplication.translate("Form", "Bear", None, QtGui.QApplication.UnicodeUTF8))
            self.label_9.setText(QtGui.QApplication.translate("Form", "Reversal of falling trend:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_15.setText(QtGui.QApplication.translate("Form", "Symetric Triangle", None, QtGui.QApplication.UnicodeUTF8))
            self.label_33.setText(QtGui.QApplication.translate("Form", "Rising gaps:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_19.setText(QtGui.QApplication.translate("Form", "Indicators and Oscilators:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_2.setText(QtGui.QApplication.translate("Form", "Triple Top", None, QtGui.QApplication.UnicodeUTF8))
            self.label_30.setText(QtGui.QApplication.translate("Form", "Morning Star", None, QtGui.QApplication.UnicodeUTF8))
            self.label_26.setText(QtGui.QApplication.translate("Form", "RSI", None, QtGui.QApplication.UnicodeUTF8))
            self.label_21.setText(QtGui.QApplication.translate("Form", "New High New Low", None, QtGui.QApplication.UnicodeUTF8))
            self.label_25.setText(QtGui.QApplication.translate("Form", "CCI", None, QtGui.QApplication.UnicodeUTF8))
            self.label_43.setText(QtGui.QApplication.translate("Form", "Evening Star", None, QtGui.QApplication.UnicodeUTF8))
            self.label_5.setText(QtGui.QApplication.translate("Form", "Formations:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_41.setText(QtGui.QApplication.translate("Form", "Sell signal:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_8.setText(QtGui.QApplication.translate("Form", "Falling Triangle", None, QtGui.QApplication.UnicodeUTF8))
            self.label_39.setText(QtGui.QApplication.translate("Form", "Rising Exhaustion Gap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_3.setText(QtGui.QApplication.translate("Form", "Head and Shoulders", None, QtGui.QApplication.UnicodeUTF8))
            self.label_13.setText(QtGui.QApplication.translate("Form", "Rising Triangle", None, QtGui.QApplication.UnicodeUTF8))
            self.label_16.setText(QtGui.QApplication.translate("Form", "Rectangle", None, QtGui.QApplication.UnicodeUTF8))
            self.pushButton.setText(QtGui.QApplication.translate("Form", "Save", None, QtGui.QApplication.UnicodeUTF8))
            self.label_20.setText(QtGui.QApplication.translate("Form", "Oscilators", None, QtGui.QApplication.UnicodeUTF8))
            self.label_24.setText(QtGui.QApplication.translate("Form", "ROC", None, QtGui.QApplication.UnicodeUTF8))
            self.label_44.setText(QtGui.QApplication.translate("Form", "Dark Cloud", None, QtGui.QApplication.UnicodeUTF8))
            self.label_40.setText(QtGui.QApplication.translate("Form", "Falling Continuation Gap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_38.setText(QtGui.QApplication.translate("Form", "Falling Breakaway Gap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_34.setText(QtGui.QApplication.translate("Form", "Rising Breakaway Gap", None, QtGui.QApplication.UnicodeUTF8))
            self.label_11.setText(QtGui.QApplication.translate("Form", "Triple Bottom", None, QtGui.QApplication.UnicodeUTF8))
            self.label.setText(QtGui.QApplication.translate("Form", "Reversal of rising trend:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_12.setText(QtGui.QApplication.translate("Form", "Falling Wedge", None, QtGui.QApplication.UnicodeUTF8))
            self.label_10.setText(QtGui.QApplication.translate("Form", "Reversed Head and Shoulders", None, QtGui.QApplication.UnicodeUTF8))
            self.label_37.setText(QtGui.QApplication.translate("Form", "Falling gaps:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_14.setText(QtGui.QApplication.translate("Form", "Continuation of trend:", None, QtGui.QApplication.UnicodeUTF8))
            self.label_17.setText(QtGui.QApplication.translate("Form", "Negetive Signal", None, QtGui.QApplication.UnicodeUTF8))
            


    
